development:
  adapter: postgresql
  database: soho_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: soho_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: soho_production
  pool: 5
  timeout: 5000